version: 0.95.0.{build}
image: Visual Studio 2019


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\Demo Plugin\
    - msbuild NppManagedPluginDemo.sln /m /verbosity:detailed /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
